project_id = "wjutvzmnvemrplpwbkyf"

[functions.import-firebase-shows]
verify_jwt = true

[functions.check-pix-notifications]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true

[functions.get-pending-payment]
verify_jwt = true

[functions.check-show-reminders]
verify_jwt = false