project_id = "wjutvzmnvemrplpwbkyf"

[functions.import-firebase-shows]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = true